import React, { useState, useEffect } from 'react';
import { FileText, Download, Crown, CheckCircle, XCircle } from 'lucide-react';
import Layout from '../../components/layout/Layout';
import PremiumGate from '../../components/common/PremiumGate';
import { useAuth } from '../../context/AuthContext';
import api from '../../utils/api';
import { formatCurrency, formatDate, CATEGORY_COLORS } from '../../utils/helpers';
import toast from 'react-hot-toast';

const ReportsPage = () => {
  const { isPremium } = useAuth();
  const [summary, setSummary] = useState(null);
  const [expenseStats, setExpenseStats] = useState(null);
  const [incomeStats, setIncomeStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [s, e, i] = await Promise.all([
          api.get('/dashboard'),
          api.get('/expenses/stats'),
          api.get('/incomes/stats'),
        ]);
        setSummary(s.data.summary);
        setExpenseStats(e.data.stats);
        setIncomeStats(i.data.stats);
      } catch { toast.error('Failed to load report data.'); }
      finally { setLoading(false); }
    };
    fetchData();
  }, []);

  const generateCSV = () => {
    if (!isPremium()) return toast.error('Upgrade to Premium for CSV export.');
    try {
      const rows = [
        ['Financial Summary Report - PEMS'],
        ['Generated:', new Date().toLocaleString()],
        [''],
        ['SUMMARY'],
        ['Total Income', summary?.totalIncome || 0],
        ['Total Expenses', summary?.totalExpense || 0],
        ['Net Balance', summary?.balance || 0],
        ['Monthly Income', summary?.monthlyIncome || 0],
        ['Monthly Expenses', summary?.monthlyExpense || 0],
        [''],
        ['EXPENSES BY CATEGORY'],
        ['Category', 'Amount', 'Transactions'],
        ...(expenseStats?.categoryStats || []).map(c => [c._id, c.total, c.count]),
        [''],
        ['INCOME BY SOURCE'],
        ['Source', 'Amount'],
        ...(incomeStats?.categoryStats || []).map(c => [c._id, c.total]),
      ];
      const csvContent = rows.map(r => r.join(',')).join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `PEMS_Report_${Date.now()}.csv`; a.click();
      URL.revokeObjectURL(url);
      toast.success('CSV report downloaded!');
    } catch { toast.error('Failed to generate CSV.'); }
  };

  const generatePDF = () => {
    if (!isPremium()) return toast.error('Upgrade to Premium for PDF download.');
    setGenerating(true);
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html>
<html>
<head><title>PEMS Financial Report</title>
<style>
  body { font-family: Arial, sans-serif; color: #333; padding: 40px; }
  h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; pb: 10px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #4f46e5; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #eee; }
  .stat { background: #f9fafb; padding: 15px; border-radius: 8px; margin: 10px 0; display: inline-block; width: 22%; }
  .stat-val { font-size: 20px; font-weight: bold; color: #4f46e5; }
</style></head>
<body>
<h1>📊 PEMS Financial Report</h1>
<p>Generated: ${new Date().toLocaleString()} | Currency: NPR (Nepali Rupees)</p>
<div>
  <div class="stat"><p>Total Income</p><p class="stat-val">रु ${(summary?.totalIncome || 0).toLocaleString()}</p></div>
  <div class="stat"><p>Total Expenses</p><p class="stat-val">रु ${(summary?.totalExpense || 0).toLocaleString()}</p></div>
  <div class="stat"><p>Net Balance</p><p class="stat-val">रु ${(summary?.balance || 0).toLocaleString()}</p></div>
  <div class="stat"><p>Monthly Spend</p><p class="stat-val">रु ${(summary?.monthlyExpense || 0).toLocaleString()}</p></div>
</div>
<h2>Expenses by Category</h2>
<table><tr><th>Category</th><th>Total (NPR)</th><th>Transactions</th></tr>
${(expenseStats?.categoryStats || []).map(c => `<tr><td>${c._id}</td><td>रु ${c.total.toLocaleString()}</td><td>${c.count}</td></tr>`).join('')}
</table>
<h2>Income by Source</h2>
<table><tr><th>Source</th><th>Total (NPR)</th></tr>
${(incomeStats?.categoryStats || []).map(c => `<tr><td>${c._id}</td><td>रु ${c.total.toLocaleString()}</td></tr>`).join('')}
</table>
<p style="margin-top:40px;color:#999;font-size:12px;">Generated by PEMS — Personal Expense Management System</p>
</body></html>`;
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `PEMS_Report_${Date.now()}.html`; a.click();
      URL.revokeObjectURL(url);
      toast.success('Report downloaded! Open in browser and Print→Save as PDF.');
      setGenerating(false);
    }, 1500);
  };

  return (
    <Layout title="Reports">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
        <div>
          <h1 className="page-title">Financial Reports</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">Download and analyze your financial reports</p>
        </div>
        {isPremium() && (
          <div className="flex gap-2">
            <button onClick={generateCSV} className="btn-secondary text-sm py-2">
              <Download size={14} />CSV
            </button>
            <button onClick={generatePDF} disabled={generating} className="btn-primary text-sm py-2">
              <Download size={14} />{generating ? 'Generating...' : 'PDF Report'}
            </button>
          </div>
        )}
      </div>

      {!isPremium() && (
        <div className="mb-6 card bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800">
          <div className="flex items-center gap-3">
            <Crown size={20} className="text-amber-500" />
            <p className="text-sm text-amber-800 dark:text-amber-300">
              <strong>Premium Feature:</strong> Upgrade to download PDF & CSV reports.
            </p>
          </div>
        </div>
      )}

      {/* Summary */}
      {!loading && summary && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
          {[
            { label: 'Total Income', value: formatCurrency(summary.totalIncome), color: 'text-emerald-600 dark:text-emerald-400' },
            { label: 'Total Expenses', value: formatCurrency(summary.totalExpense), color: 'text-red-600 dark:text-red-400' },
            { label: 'Net Balance', value: formatCurrency(summary.balance), color: 'text-indigo-600 dark:text-indigo-400' },
            { label: 'This Month', value: formatCurrency(summary.monthlyExpense), color: 'text-purple-600 dark:text-purple-400' },
          ].map(s => (
            <div key={s.label} className="card text-center py-4">
              <p className={`text-xl font-bold ${s.color}`}>{s.value}</p>
              <p className="text-xs text-gray-400 dark:text-gray-500 mt-0.5">{s.label}</p>
            </div>
          ))}
        </div>
      )}

      {/* Category Table */}
      {!loading && expenseStats?.categoryStats?.length > 0 && (
        <div className="card mb-6">
          <h2 className="section-title mb-4">Expense Category Breakdown</h2>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-100 dark:border-gray-700">
                  <th className="text-left py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">Category</th>
                  <th className="text-right py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">Amount</th>
                  <th className="text-right py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">Transactions</th>
                  <th className="text-right py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">Avg</th>
                  <th className="text-right py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase">Share</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50 dark:divide-gray-700/50">
                {expenseStats.categoryStats.map((c, i) => {
                  const pct = expenseStats.totalAll > 0 ? (c.total / expenseStats.totalAll * 100).toFixed(1) : 0;
                  return (
                    <tr key={i} className="hover:bg-gray-50/50 dark:hover:bg-gray-700/20">
                      <td className="py-3">
                        <div className="flex items-center gap-2">
                          <div className="w-3 h-3 rounded-full" style={{ backgroundColor: CATEGORY_COLORS[c._id] || '#6366f1' }} />
                          <span className="text-sm font-medium text-gray-700 dark:text-gray-300">{c._id}</span>
                        </div>
                      </td>
                      <td className="py-3 text-right text-sm font-bold text-gray-800 dark:text-gray-200">{formatCurrency(c.total)}</td>
                      <td className="py-3 text-right text-sm text-gray-500 dark:text-gray-400">{c.count}</td>
                      <td className="py-3 text-right text-sm text-gray-500 dark:text-gray-400">{formatCurrency(c.total / (c.count || 1))}</td>
                      <td className="py-3 text-right text-sm font-medium" style={{ color: CATEGORY_COLORS[c._id] || '#6366f1' }}>{pct}%</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {!isPremium() && <PremiumGate feature="PDF & CSV Report Downloads" />}
    </Layout>
  );
};

export default ReportsPage;
